# Generated by Django 4.1.6 on 2023-02-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('staffName', models.TextField(max_length=100)),
                ('staffPhoneNumber', models.CharField(max_length=11)),
                ('staffPassword', models.CharField(max_length=9, null=True)),
            ],
        ),
    ]
