# Generated by Django 4.1.6 on 2023-02-17 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyGo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaQ',
            fields=[
                ('faqID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('productName', models.TextField(max_length=100)),
                ('productPrice', models.IntegerField()),
                ('productQuantity', models.IntegerField()),
                ('productExpirationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockIn', models.TextField()),
                ('stockOut', models.TextField()),
                ('faqID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyGo.faq')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyGo.product')),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyGo.staff')),
            ],
        ),
    ]
