# Generated by Django 4.1.6 on 2023-02-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyGo', '0004_alter_staff_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.IntegerField(null=True),
        ),
    ]
