# Generated by Django 4.1.6 on 2023-02-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyGo', '0005_staff_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staff',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_management',
            name='faqID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EasyGo.faq'),
        ),
        migrations.AlterField(
            model_name='stock_management',
            name='stockIn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_management',
            name='stockOut',
            field=models.TextField(null=True),
        ),
    ]
