# Generated by Django 4.1.6 on 2023-02-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyGo', '0006_alter_staff_managers_remove_staff_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staffName',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffPhoneNumber',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='stock_management',
            name='faqID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EasyGo.faq'),
        ),
        migrations.AlterField(
            model_name='stock_management',
            name='productID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EasyGo.product'),
        ),
    ]
