# Generated by Django 4.1.6 on 2023-02-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyGo', '0007_alter_staff_staffname_alter_staff_staffphonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_management',
            name='faqID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EasyGo.faq'),
        ),
        migrations.AlterField(
            model_name='stock_management',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EasyGo.product'),
        ),
        migrations.AlterField(
            model_name='stock_management',
            name='staffID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EasyGo.staff'),
        ),
    ]
