# Generated by Django 4.1.6 on 2023-02-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyGo', '0008_alter_stock_management_faqid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_management',
            name='faqID',
        ),
    ]
