# Generated by Django 4.1.6 on 2023-02-21 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyGo', '0009_remove_stock_management_faqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffPassword',
            field=models.CharField(default='null', max_length=9),
        ),
        migrations.CreateModel(
            name='FaQ_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('faqID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyGo.faq')),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyGo.staff')),
            ],
        ),
    ]
