# Generated by Django 4.1.6 on 2023-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyGo', '0010_alter_faq_question_alter_staff_staffpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
        migrations.RemoveField(
            model_name='faq_management',
            name='answer',
        ),
        migrations.AlterField(
            model_name='faq_management',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
