# Generated by Django 4.1.6 on 2023-02-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyGo', '0012_alter_product_productexpirationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productExpirationDate',
            field=models.DateField(),
        ),
    ]
